### ISSUE TITLE
Restore "add projects" modal on homepage 

### ISSUE THREAD

**Issue by seanknox** [brigadecore/kashti#106]
https://github.com/Azure/kashti/pull/105 removed the modal library we had been using (foundation-apps). This is a task to bring back with a maintained package. Ideas:

- foundation-sites
- bootstrap

we just need the modal javascript, so we might be able to require a small subset of the UI frameworks to accomplish that.

**Comment by radu-matei** [comment]
Kashti is read-only for now. So it is not able to change the state of projects or builds.
We can revisit this later, but closing for now. Feel free to reopen.
