### ISSUE TITLE
Build timeline isn't respecting job ordering?

### ISSUE THREAD

**Issue by mumoshu** [brigadecore/kashti#124]
Environment: kashti-0.1.0 installed by following the instruction in https://github.com/Azure/kashti/blob/master/docs/install.md#kubernetes-installation w/ 8e51fd687570820ec27ed4785b54b07c1321f916

Hi, thanks for maintaining a great project 👍 

Not really sure this is an expected thing or not but please let me report anyway.

I have a brigade.js which looks exactly like:

```js
const { events, Job, Group } = require('brigadier')

events.on("exec", (brigadeEvent, project) => {
  var one = new Job("one", "alpine:3.4", ["echo hello one"])
  one.useSource = false

  one.run().then(() => {
    var two = new Job("two", "alpine:3.4", ["echo hello two"])
    two.useSource = false
    two.run()
  })
})
```

which results in a build timeline like the below when `brig run -f brigade.js myghuser/myghrepo`:

![image](https://user-images.githubusercontent.com/22009/34721962-2df2a348-f588-11e7-8326-e3764aed8a8d.png)

FWIW, what I had expected to see in the build timeline was that `the job two looks like it has started AFTER the job one had finished`.

However, what I saw looks like `both one and two started at the same time`, which isn't true.

Would it make sense to make the horizontal bar for the job `two` starts after the job `one` in this case?

**Comment by flynnduism** [comment]
Thanks for the feedback @mumoshu - you're correct!

It isn't rendering correctly, and is on our [list of fixes](https://github.com/Azure/kashti/projects/1) - we'll be working on this timeline chart shortly.

**Comment by radu-matei** [comment]
Closing in favour of #14, which offers some more context.
