### ISSUE TITLE
Gantt Charting for jobs in a build

### ISSUE THREAD

**Issue by technosophos** [brigadecore/kashti#14]

**Comment by flynnduism** [comment]
Here's some context for this issue:

![screen shot 2017-12-04 at 11 38 31 am](https://user-images.githubusercontent.com/686194/33572619-4e3a513a-d8e8-11e7-97ef-a6da4b10c5e6.png)

Each build view contains a timeline chart at the top which breaks down the list of child jobs (if any) that ran within the build process. It's intended to be a simple chronological visual of what happened. 

I'd researched different chart libraries and I think [angular-gantt](https://github.com/angular-gantt/angular-gantt) could be a good fit - see what you think though, perhaps there's a better way to approach this.

Right now, the build view lists a bunch of `<div>` via `ngRepeat` for jobs in a build, and I've hard-coded their layout via CSS to mockup a sample timeline - a fake it 'til you make it stopgap.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
