### ISSUE TITLE
Dashboard page should automatically poll for updates from API and display changes

### ISSUE THREAD

**Issue by seanknox** [brigadecore/kashti#164]
As a user I would like to see project status automatically update on the dashboard 
So I see changes in real-time without refreshing the page

Acceptance Criteria:
- The dashboard polls the Brigade API for changes every 5 seconds and re-renders the project cards that have a changed status 
- Projects who have don't have a different status are not updated

Engineering notes:
- Since the ProjectService already returns Observables to the Dashboard component (via a route resolver), I think it's just a matter of adding the polling to `api-project.service.ts`

**Comment by seanknox** [comment]
@flynnduism an idea I had that should be relatively straightforward to implement here and on other pages.

**Comment by radu-matei** [comment]
The status is still missing from the dashboard:

![status](https://user-images.githubusercontent.com/13103165/42938481-1ba6e3fc-8b5b-11e8-8d77-378456d5bb54.PNG)

The simplest way would be to make a request for the latest build and display the status here, without polling (at least at first).

![status2](https://user-images.githubusercontent.com/13103165/42938482-1bc3c990-8b5b-11e8-8f3d-e6b78657cda7.PNG)

**Comment by pihalve** [comment]
I really support this issue with auto-refreshing the dashboard, since it is so annoying having to press F5 a "million" times when executing a pipeline. The sooner the better :-)

**Comment by radu-matei** [comment]
See #260
