### ISSUE TITLE
Angular test file needs imports ordered

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/kashti#230]
It appears Angular Zone.js needs imports ordered in `test.ts` -  https://github.com/angular/zone.js/issues/404

This means, as it was pointed out by @vdice in https://github.com/Azure/kashti/pull/227#discussion_r222376872, that we currently cannot have the VS Code functionality that automatically orders the imports for that particular file.

But the issue is that, in its current form, the VS Code `source.organizeImports ` cannot be parametrized for a specific file / file type / directory / extension, as it is explained in the relevant VS Code issue - https://github.com/Microsoft/vscode/issues/35350

As we'd really like to be able to have the ability for auto ordering the imports, this issue is to keep track of a workaround for adding the functionality, but ignore it for some particular files.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
