### ISSUE TITLE
UI breaking when "commit" field of undefined

### ISSUE THREAD

**Issue by arunramachandran15** [brigadecore/kashti#235]
I installed kashti by cloning repo and also tried different releases.
helm install --name custkashti ./ --set service.type=NodePort --set brigade.apiServer=http://18.212.111.104:30656 --set image.tag=v0.3.0-rc1

Brigade version : brigade-0.9.0

As attached the UI is broken

Dashboard : http://18.212.111.104:30521/dashboard
![listview](https://user-images.githubusercontent.com/10073043/47615145-5aba9f00-dad1-11e8-8a08-7d102a67e427.png)

On project select: 
![select](https://user-images.githubusercontent.com/10073043/47615154-8473c600-dad1-11e8-93a2-b4276d042ea7.png)

On click details >>
![image](https://user-images.githubusercontent.com/10073043/47615179-e2081280-dad1-11e8-9348-43ab857f2815.png)

Console log:
![image](https://user-images.githubusercontent.com/10073043/47615223-6a86b300-dad2-11e8-9537-8b3bfba31141.png)

Please let me know how to install stable kashti.

**Comment by radu-matei** [comment]
Hey, @arunramachandran15!
First of all, thanks for reporting this!

Could you please share the error in the first two pages as well?
Also, the response from the API in all cases would be helpful.

Thanks!

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
