### ISSUE TITLE
Add event type in the builds list

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/kashti#241]
When using Brigade as CI, some of the events are `noop` (such as `check_suite_completed` from the GitHub checks API), and most of the times we want to see the build logs from other events.

However, from the current build list, you cannot tell which build executed our checks and which are just informational from GitHub:

<img width="1080" alt="screen shot 2019-01-28 at 17 22 47" src="https://user-images.githubusercontent.com/13103165/51846139-ad4e6600-2321-11e9-95fa-19a65276b421.png">

It would be nice to see the event type of the build in the build list.

**Comment by krancour** [comment]
This was addressed by #255
