### ISSUE TITLE
Proposal: link to Brigade documentation from Kashti

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/kashti#257]
Right now, there are two links in Kashti that point to the issue queue and documentation for Kashti - we should also add a link to the Brigade docs.

**Comment by saksham93** [comment]
@radu-matei As far as I understand we need to add a button in the left vertical bar(shown below). What should the icon of brigade docs look like? Should it be like the Kashti docs?

![image](https://user-images.githubusercontent.com/37399540/69003465-1be5ca00-091c-11ea-80ed-0ebf2fc53e01.png)

**Comment by radu-matei** [comment]
Added in #277.
