### ISSUE TITLE
Rework the build view UI

### ISSUE THREAD

**Issue by flynnduism** [brigadecore/kashti#259]
Following on from #258. The UI for the build + job info could better balance metadata and logs for the different elements.
 
![67811647-7e088900-fa5a-11e9-8431-d2be48fb11a3 (1)](https://user-images.githubusercontent.com/686194/67815763-1146bc00-fa65-11e9-9753-0936187dd35e.png)

The worker logs (black textarea at the bottom) are a bit buried, shown after the build is finished, though this is running in parallel to the jobs. I think a tabbed approach could be useful to balance keeping the top level info and the logs in view at the same time. 

<img width="993" alt="Screen Shot 2019-10-29 at 3 47 14 PM" src="https://user-images.githubusercontent.com/686194/67815897-78fd0700-fa65-11e9-9723-117d5a3cc040.png">

**Comment by radu-matei** [comment]
This would be amazing!

**Comment by radu-matei** [comment]
ref #33 #14 #213

**Comment by carolynvs** [comment]
This would be really helpful. For builds with lots of steps, it can be a very long scroll to find the part that failed and find the relevant logs.

**Comment by krancour** [comment]
Highly in favor of this.

cc @ danieldelao

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
