### ISSUE TITLE
Link in project view without builds points old docs

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/kashti#264]
It should point to https://docs.brigade.sh/topics/scripting/

![image](https://user-images.githubusercontent.com/13103165/67891444-d9488300-fb0f-11e9-9f28-29fb54469f52.png)

**Comment by saksham93** [comment]
I am working on this issue.

**Comment by saksham93** [comment]
Raised the PR for the same

**Comment by saksham93** [comment]
Raised a new PR with correction
