### ISSUE TITLE
Show context about build on build list page

### ISSUE THREAD

**Issue by carolynvs** [brigadecore/kashti#267]
While I'm looking at the build listing, it's usually because github has let me down. For example a notification wasn't sent back to github and now I can't tell why a build never reported back and I need more info about what's going on. Did it kick off? Did it fail? Is it still running?

But finding that build that I'm looking for in Kashti can be very hard if I don't have a direct link to it.

The build page doesn't give me enough context to know which build is the one I want, so I need to click into each one and then dig into each one's logs

![Screen Shot 2019-10-31 at 4 39 05 PM](https://user-images.githubusercontent.com/1368985/67988103-06269400-fbfd-11e9-8d88-ab68bf7bedc6.png)

But even when I look at a build, often I can't tell what it was for (which PR? which tag?) or why it doesn't have any logs or why it says 0 jobs. Honestly it looks broken, like nothing ran? It's not clear, I'm sure as a maintainer you know but to a user, there's not enough information.

![Screen Shot 2019-10-31 at 4 40 34 PM](https://user-images.githubusercontent.com/1368985/67988278-7e8d5500-fbfd-11e9-871a-f790b5067088.png)

What I needed to see on the build listing page and the individual build page was some type of context information. For a build from a tag, I need to know the tag. For the build from a pull request, I need to know the PR number, and would really appreciate a link back to the PR.

I'm not sure why some builds have no useful information at all, but at least if I could see which build it was for, that would be a start. 😀

**Comment by krancour** [comment]
This should have been closed by #274

As long as a sufficiently new release of the GitHub gateway is being used, builds related to events from that gateway should have useful titles applied to them and Kashti should show those titles in place of the build ID if/when they exist.
