### ISSUE TITLE
Can't see white text at top of build status page

### ISSUE THREAD

**Issue by carolynvs** [brigadecore/kashti#268]
The build status page sometimes shows text in white on top of the gray background, so it's not easy to read. When I hover over the text, I get a blue box so then I can read it but before then it's not readable.

![Screen Shot 2019-10-31 at 4 40 34 PM](https://user-images.githubusercontent.com/1368985/67988583-71bd3100-fbfe-11e9-9a69-91db4eb42d44.png)

![Screen Shot 2019-10-31 at 4 50 02 PM](https://user-images.githubusercontent.com/1368985/67988608-800b4d00-fbfe-11e9-8c2f-bad86df51b3c.png)

I've verified in both Firefox and Safari on MacOS.

**Comment by saksham93** [comment]
I am working on this issue.

**Comment by saksham93** [comment]
Raised the PR for the same.
The view is now visible as below:
![image](https://user-images.githubusercontent.com/37399540/69003412-41be9f00-091b-11ea-94d2-2f79bb1e0e9c.png)

**Comment by radu-matei** [comment]
@saksham93 - is there a PR addressing this?
I can't seem to find it. Thanks!

**Comment by saksham93** [comment]
@radu-matei This issue is addressed by #272 .

**Comment by radu-matei** [comment]
Ah, missed that - thanks a lot!
