### ISSUE TITLE
Fixed sorting strategy for builds

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/kashti#270]
#260 started updating the builds component.
We need to fix the strategy for ordering them.

(They should probably be ordered by build ID)

**Comment by radu-matei** [comment]
^^ The underlying issue here is that the Brigade API does not return items in an ordered list.

**Comment by krancour** [comment]
2.0 API will sort events (previously called builds) by age-- newest first. That should probably fix this.

If other sort orders need to be supported, request that as an issue against. Brigade 2.0.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
