### ISSUE TITLE
CI: Serve Kashti site preview for PRs?

### ISSUE THREAD

**Issue by vdice** [brigadecore/kashti#278]
Wondering if it would be possible to serve Kashti previews for PRs a la Netlify builds serving static docs.  Perhaps each PR build could point to our dogfood Brigade api server (api.brigade.sh) ?

**Comment by radu-matei** [comment]
We can do that, and we should, great suggestion!

Pinging @flynnduism, who set up most of our Netlify builds.

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
