### ISSUE TITLE
Add Node modules audit build target for Kashti

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/kashti#279]
For the Brigade worker we added a build target run for all pull requests that runs `yarn audit`, which catches any NPM module vulnerability that might have appeared since adding that specific version - see https://github.com/brigadecore/brigade/blob/9cd050ac7f3ea82e44cbde6164d4dbf681dc5c9b/Makefile#L97-L99

We should add this target to Kashti as well, even more importantly, since we have more direct dependencies that end up in production.

**Comment by saksham93** [comment]
Raised PR for this. Can you please suggest if it is correct or not.

**Comment by radu-matei** [comment]
Added in #280.
