### ISSUE TITLE
Proposal: Move into main brigade project repo

### ISSUE THREAD

**Issue by krancour** [brigadecore/kashti#284]
I can't quite identify what cases exist where Kashti is useful in the absence of Brigade, which is a signal to me that it doesn't need to be its own project. I'd like to propose that as we look toward Brigade 2.0 (and Kashti 2.0) that we might consider folding Kashti into the main Brigade project.

The primary benefit of this would be that it would be much easier to coordinate changes that span the front-end and back-end (Brigade's API server) in just a single PR.

**Comment by flynnduism** [comment]
I think this would be neat too.

The only downside I can think off is the additional noise it could add to the core project - mostly around tons of angular dependencies, security vulns, etc but should mean a much cleaner workflow overall

**Comment by krancour** [comment]
> mostly around tons of angular dependencies

::grumble:: You're right about that.

Let's put some thought into how we can best mitigate that. In the end... maybe we don't do this. 🤷‍♂

**Comment by krancour** [comment]
My original thinking on this was wrong.

> I can't quite identify what cases exist where Kashti is useful in the absence of Brigade, which is a signal to me that it doesn't need to be its own project.

Kashti may not be useful without Brigade, but Brigade _is_ useful without Kashti.

Based on that, I believe Kashti should remain in Brigade's "orbit" and not be part of Brigade itself.
