### ISSUE TITLE
Kashti doesn't process ansi escape sequences resulting in garbled output when an error occurs

### ISSUE THREAD

**Issue by LittleColin** [brigadecore/kashti#293]
The logging in brigade uses ansi escape sequences to colour the log messages but this is not handled in Kashti. You could use something like https://github.com/drudru/ansi_up to convert the colours into html. For example

```
  [0m[97m[41mError[0m[90m:[0m[37m [0m[97mtime limit (900000 ms) exceeded[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mk8s.js[0m[90m:[0m[93m706[0m[37m [0m[37mTimeout.setTimeout [as _onTimeout][0m
[0m  [0m  [0m[90m/home/src/dist/k8s.js:706:24[0m
[0m  [0m
[0m
```

**Comment by krancour** [comment]
@flynnduism @radu-matei any opinions on this?

Front-end isn't my forte, but after a quick glance at the ansi_up package, this looks like it could be easy enough.

**Comment by flynnduism** [comment]
@LittleColin thanks for creating this issue. Adding `ansi` support is a great idea!

**Comment by radu-matei** [comment]
Ooh, this looks like a great suggestion for Kashti - I will definitely have a look at how this could work, thanks for the suggestion!

That being said, this is part of a larger issue with the Brigade worker and ANSI characters, which I had unsuccessfully tried to strip in the past - also see https://github.com/brigadecore/brigade/issues/418,  https://github.com/brigadecore/brigade/issues/438, and https://github.com/brigadecore/brigade/issues/754.

**Comment by krancour** [comment]
@radu-matei but what about jobs that might produce colored output?

This seems like a nice catch-all.

**Comment by radu-matei** [comment]
I agree that this is a great solution for Kashti, and we should implement it.

Stripping ANSI characters however would work for all other instances where worker logs are displayed without ANSI support (some terminals?).

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
