### ISSUE TITLE
Need a Brigade v2-compatible rewrite

### ISSUE THREAD

**Issue by krancour** [brigadecore/kashti#319]
This issue appears in this issue queue for lack of a better or more visible place.

This issue calls for an _all new_ Brigade v2-compatible replacement for the existing v1-compatible Kashti.

We should move away from Angular and toward React. Brigade v2 API/SDKs should also make this a _relatively_ easy effort.

Note a prototype already does exist, so anyone wishing to take up this effort probably should not plan on starting completely from scratch. https://github.com/krancour/kashti-tng

Also note that early-in-career developers may be able to work on this as a Google Summer of Code project!

**Comment by DhairyaBahl** [comment]
@krancour I would like to work on this idea under GSoC'22.

Kindly tell me how can I start working on this as soon as possible ! Really excited to work on this project.

**Comment by DhairyaBahl** [comment]
@krancour Kindly tell me in which part you are facing issue with the application ? I've done GSoC last year as well ! I'll see if I can help you out with that 😄

**Comment by krancour** [comment]
This issue is superseded by https://github.com/brigadecore/brigade-dashboard/issues/4.
