### ISSUE TITLE
Expired builds causing 404s

### ISSUE THREAD

**Issue by flynnduism** [brigadecore/kashti#53]
When I browse the UI, i'm getting a bunch of 404s for API endpoints in the console:

```
e.g.
http://acid-api.technosophos.me:7745/v1/project/01bz3j29xmz4dhs99xahm1q9bh
http://acid-api.technosophos.me:7745/v1/project/01bzzn07g488przds1x7n21p2v
http://acid-api.technosophos.me:7745/v1/project/01bzzmz498aqh18hc7j5erjxmm/builds
```

I think these are endpoints that **did exist**, but have expired? 

Is there a way the UI / API can know the difference between a build which still has data, and one that has expired? Not for MVC, but important UX for launch, to have better error states.

**Comment by radu-matei** [comment]
We could catch any 404s and display a fading red modal at the top saying that the build is no longer available.

For jobs, we could enter the job view and wait for logs to update.
