### ISSUE TITLE
console.log doesn't seem to write anywhere

### ISSUE THREAD

**Issue by squillace** [brigadecore/kashti#86]
perhaps user error. http://kashti.squillace.io/kashti/#!/build/01c0axkwdsawctvb90p4yg1gzk displays the results of the brigade.js file located https://github.com/squillace/GiraffeSample/blob/master/brigade.js. 

The jobs fire properly:

![image](https://user-images.githubusercontent.com/1422718/33518390-02f09338-d749-11e7-8abf-26169345aa6d.png)

But the console.log calls do not seem to be visible in any way in the log area of kashti (see link above). Where do they appear? Instead, if the call succeeded I see the 200 HTTP response code.

**Comment by radu-matei** [comment]
Console logs are handled by the Brigade worker, and the logs are visible in Kashti.

For example, this `console.log` in the `brigade.js` file for Kashti itself is visible in the dashboard logs:

![Screen Shot 2020-01-07 at 12 21 26 PM](https://user-images.githubusercontent.com/13103165/71926483-4ac43380-3148-11ea-9342-c3c0be3f81b5.png)

**Comment by squillace** [comment]
I'll have a look. thanks!
